services:
  postgres:
    image: postgres:15
    container_name: smartapp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartapp_db
    ports:
      - "5432:5432"
    volumes:
      - smartapp_postgres_data:/var/lib/postgresql/data

volumes:
  smartapp_postgres_data:
